batch_size: 24
epochs: 99
past_length: 10
future_length: 10
log_interval: 1
test_interval: 1
lr: 5.e-4
epoch_decay: 6
lr_gamma: 0.9
nf: 64
channels: 32
time_exp: 0
weight_decay: 1.e-11
scale: 100
apply_decay: true
part_noise: true
denoise_mode: past
max_weight: 5
weighted_loss: false

kernel_size: [5, 2]
graph_args_j:
  layout: 'cmu'
  strategy: 'distance'
graph_args_p:
  layout: 'cmu'
  strategy: 'distance'
graph_args_b:
  layout: 'cmu'
  strategy: 'distance'

